import { Inter } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="root" className="w-full min-h-[100dvh] flex flex-col justify-start items-center">
        {children}
        </div>
      </body>
    </html>
  );
}
